name: "TestReports"
reports:
  enabled: true
  cooldown: 15
  require-reason: true
  notify-console: true
  reason-presets: ["Hacking", "Chat Abuse", "Griefing"]
discord-integration:
  enabled: false
  webhook-url: ""
  embed:
    title: "SnowReports"
    hex-color: "#03c2fc"
debug:
  allow-self-report: false
metrics: true
check-for-updates: true