name: SnowReports
version: '2.0.0'
main: dev.snowz.snowreports.SnowReports
author: SnowzNZ
description: SnowReports, a report plugin for versions 1.8.8 to 1.20.1.
website: https://modrinth.com/plugin/snowreports
#folia-supported: true

commands:
  delreport:
    description: Delete a report
    usage: /<command> <Report ID>
    permission: snowreports.admin
  report:
    description: Report a player
    usage: /<command> <player> <reason>
    permission: snowreports.report
  reports:
    description: Get a player's reports
    usage: /<command> <player>
    permission: snowreports.admin

permissions:
  snowreports.report:
    default: true
    description: Report
  snowreports.report.receive:
    default: op
    description: Receive reports
  snowreports.bypass.cooldown:
    default: op
    description: Bypass the report cooldown
  snowreports.admin:
    default: op