name: Build

on:
  pull_request:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: "8"
        distribution: "temurin"
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: SnowzNZ/SnowReports
