name: Build SnowReports

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: "8"
        distribution: "temurin"
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Upload all artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SnowReports
        path: target/SnowReports-*.jar
