name: SnowReports
version: '${version}'
main: dev.snowz.snowreports.paper.SnowReports
loader: dev.snowz.snowreports.paper.SnowReportsLoader
author: Snowz
description: Lightweight, customizable player reporting plugin.
api-version: '1.20.6'
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false
      join-classpath: true
